### ISSUE TITLE
DUS-FbW10

### ISSUE THREAD

**Issue by alperece** [DCI-TechEd/GitHub-Student-Developer-Pack#3]
[
   {
      "studentId":"01",
      "email":"markennaol20@gmail.com",
      "class":"FbW10",
      "firstName":"Afework",
      "lastName":"Bisrate"
   },
   {
      "studentId":"02",
      "email":"adebowal.bakare@gmail.com",
      "class":"FbW10",
      "firstName":"Adebowale Daniel",
      "lastName":"Bakare"
   },
   {
      "studentId":"03",
      "email":"costelcuconoiu@gmail.com",
      "class":"FbW10",
      "firstName":"Costel",
      "lastName":"Cuconoiu"
   },
   {
      "studentId":"04",
      "email":"adebowal.bakare@gmail.com",
      "class":"FbW10",
      "firstName":"Marcio Jorge",
      "lastName":"Duarte"
   },
   {
      "studentId":"05",
      "email":"annas.kalu1@gmail.com",
      "class":"FbW10",
      "firstName":"Onyemaechi",
      "lastName":"Kalu"
   },
   {
      "studentId":"06",
      "email":"k.meyer.duisburg@gmail.com",
      "class":"FbW10",
      "firstName":"Kristof",
      "lastName":"Meyer"
   },
   {
      "studentId":"07",
      "email":"parsa_monfared20@yahoo.com",
      "class":"FbW10",
      "firstName":"Monfaredidoust Patavani",
      "lastName":"Parviz"
   },
   {
      "studentId":"08",
      "email":"naumanntim89@gmail.com",
      "class":"FbW10",
      "firstName":"Tim",
      "lastName":"Naumann"
   },
   {
      "studentId":"09",
      "email":"Younesitoo@hotmail.fr",
      "class":"FbW10",
      "firstName":"Younes",
      "lastName":"Outeha"
   },
   {
      "studentId":"10",
      "email":"adrian911225@gmail.com",
      "class":"FbW10",
      "firstName":"Cristian Adrian",
      "lastName":"Rogojina"
   },
   {
      "studentId":"11",
      "email":"majdwarrrak@gmail.com",
      "class":"FbW10",
      "firstName":"Majd",
      "lastName":"Warrak"
   }
]

**Comment by LeandroDCI** [comment]
Hi @alperece I created the access codes for your students [here](https://github.com/DCI-TechEd/dci-github-student-developer-pack-alperece/blob/master/access_codes.md). Check the info in the md... let me know if you need help of have questions ;)
